version: "3"

services:
  frontend:
    container_name: shopping-frontend
    build:
      context: front-end
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ./front-end/.env

  backend:
    container_name: shopping-backend
    build:
      context: back-end
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3001:3001
    env_file:
      - ./back-end/.env
    links:
      - db
    depends_on:
      - db

  db:
    container_name: mysql
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "shopping-cart-zone"
      MYSQL_USER: "root"
      #MYSQL_ROOT_PASSWORD=prisma

volumes:
  dbdata:
    driver: local # is already local by default
